export const images = {
    hero_img: require("../images/hero-img.png"),
    shape: require("../images/shape.png"),
    yoga_retreat: require("../images/yoga-retreat.jpg"),
    quote_img: require("../images/quote-img.jpg"),
    yin_yoga: require("../images/yinyoga-class.jpg"),
    hatha_yoga: require("../images/hathayoga-class.jpg"),
    class_yoga: require("../images/yoga-class.jpg"),
    hero_img_cropped: require("../images/hero-img-cropped.png"),
    gallery: require("../images/gallery.jpg"),
    gallery_food: require("../images/gallery-food.jpg"),
    gallery_retreat: require("../images/gallery-retreat.jpg"),
    gallery_teacher: require("../images/gallery-teacher.jpg"),
    gallery_stretch: require("../images/gallery-stretch.jpg"),
    gallery_waterfall: require("../images/gallery-waterfall.jpg"),
};